pipeline:
  setup:
    image: docker
    commands:
      - mkdir rootfs
      - wget 'http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz' -O ArchLinuxARM.tar.gz
      - tar xf ArchLinuxARM.tar.gz -C rootfs/
      - tar cfj ArchLinuxARM.tar.xz -C rootfs .     # You have to thank Docker Symlinks for this ...
      - rm ArchLinuxARM.tar.gz
      - docker build --rm -t pixelclinux/arch-linux:latest .
      - docker save -o pixelc-arch.tar pixelclinux/arch-linux:latest
      - mkdir docker-layers
      - mkdir docker-rootfs
      - tar -xvf pixelc-arch.tar -C docker-layers
      - for i in docker-layers/**/layer.tar; do tar -xvf -C docker-rootfs/; done
      - tar -cfj pixelc-arch.tar.xz docker-rootfs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: pixelc-arch.tar.xz
    when:
      event: tag
