pipeline:
  setup:
    image: docker
    commands:
      - mkdir rootfs
      - wget 'http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz' -O ArchLinuxARM.tar.gz
      - tar xf ArchLinuxARM.tar.gz -C rootfs/
      - tar cfj ArchLinuxARM.tar.xz -C rootfs .     # You have to thank Docker Symlinks for this ...
      - rm ArchLinuxARM.tar.gz
      - docker build --rm -t pixelclinux/arch-linux:latest .
      - docker export pixelclinux/arch-linux:latest > pixelc-arch.tar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: pixelc-arch.tar
    when:
      event: tag
